---

- name: Install mysql-server and python-pymysql 
  apt:
    name: 
    - mysql-server
    - python-pymysql # It's nescesary to configure MySQL by Ansible
    state: present
    update_cache: true
    force_apt_get: yes

- name: Updating Ansible Info
  setup:

- name: Enable mysql-server
  service: 
    name: mysql
    enabled: yes
    state: started

- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    check_implicit_admin: yes
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes
#  ignore_errors: yes

- name: generate Mysql root password
  shell: < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-16};echo;
  register: root_passwd
  run_once: true

- set_fact:
    my_root_pass: "{{ root_passwd.stdout }}"

- name: Set root password
  mysql_user:
    name: root
    host_all: yes
    password: "{{ my_root_pass }}"
    check_implicit_admin: yes
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes
#  ignore_errors: yes